wm_error: Allow the use of __FUNCTION__ or __func__ when available,
.. and disable -Wpedantic for gcc >= 4.6 and clang. This uncripples
debug messages when not building in c99 mode since commit 473103367
Reference issue: https://github.com/Mindwerks/wildmidi/pull/243