_WM_GLOBAL_ERROR: if werrno is out of [0..WM_ERR_MAX-1] bounds, set it to WM_ERR_MAX so that it prints 'Invalid error code'. The errors array has WM_ERR_MAX+1 members for this purpose already.